spring.application.name=learningSpringBoot

//for@Value
payment-gateway.type="RazorPay"
payment-gateway.retryCount=6
payment-gateway.enabled=true
payment-gateway.timeOut=10

//for@ConfigurationProperties
payment-properties.type="GooglePay"
payment-properties.retryCount=5
payment-properties.enabled=true
payment-properties.timeOut=5

